### ISSUE TITLE
SecurityHub just receives alerts in Audit account 

### ISSUE THREAD

**Issue by HarleyB123** [schubergphilis/terraform-aws-mcaf-landing-zone#114]
Hi!

Was just checking something here:

```
resource "aws_securityhub_account" "default" {
  provider = aws.audit
}
```

won't this just create SecurityHub in the Audit account, but not assign it any members, make it the delegated admin, or receive findings from the other AWS accounts in the organisation?

Compare this to:

```
resource "aws_securityhub_account" "default" {
  provider = aws.audit
}

resource "aws_securityhub_organization_admin_account" "example" {
   admin_account_id = var.control_tower_account_ids.audit
}

resource "aws_securityhub_organization_configuration" "example" {
   provider = aws.audit
   auto_enable = true
}
```

**Comment by marwinbaumannsbp** [comment]
Hey @HarleyB123 , thank you for your comment. You are right this was a manual action up until now and I created this issue in the provider https://github.com/hashicorp/terraform-provider-aws/issues/17287 as a reminder to add this. I see the community already picked it up which is great! https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_organization_admin_account . I'll put this on our next sprint to pick up, but feel free to open a PR if you like.

**Comment by HarleyB123** [comment]
Cool, thanks for the quick reply @marwinbaumannsbp ! Yeah happy to put a PR in. Should note though that when I applied it with the change locally, the SNS messages get very heavy and frequent - might need a design change there

**Comment by marwinbaumannsbp** [comment]
Hey @HarleyB123 this is a known issue indeed and we are working on that :-)
