### ISSUE TITLE
Data sources which refer to Audit- and Loggingaccount Cloudwatch log groups no longer found after Control Tower update to version 3.0

### ISSUE THREAD

**Issue by davealtenasbp** [schubergphilis/terraform-aws-mcaf-landing-zone#178]
With the update to Control Tower v3.0, [Cloudtrail trails are removed per stack and an organization trail is created for the environment](https://docs.aws.amazon.com/en_us/controltower/latest/userguide//2022-all.html#version-3.0). 

The data sources in [data.tf](https://github.com/schubergphilis/terraform-aws-mcaf-landing-zone/blob/master/data.tf#L11) on lines [11](https://github.com/schubergphilis/terraform-aws-mcaf-landing-zone/blob/001bf5508c263367ce09b44813bdccf8f52bf2e9/data.tf#L11) and [18](https://github.com/schubergphilis/terraform-aws-mcaf-landing-zone/blob/001bf5508c263367ce09b44813bdccf8f52bf2e9/data.tf#L18) which refer to the Cloudwatch log groups associated with these Cloudtrail logs, cannot find these log groups as the Control Tower update removes these.

**Comment by marwinbaumannsbp** [comment]
https://jira.schubergphilis.com/browse/GCTAM-80 For internal reference
